server:
  port: 8086 # The new public entry point

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Auto-create routes based on service names
          lower-case-service-id: true
      routes:
        - id: stable-match-route
          uri: lb://stable-match
          predicates:
            - Path=/api/solver/**
        - id: pref-schedule-route
          uri: lb://pref-schedule
          predicates:
            - Path=/api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/