server:
  port: 8082
spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: lab02HW
  profiles:
    active: dev
#  sql:
#    init:
#      mode: always

app:
  greeting: "Hello from application.yml"

management:
  endpoints:
    web:
      exposure:
        include: info


logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.boot.sql.init: DEBUG