version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab04-rabbitmq
    ports:
      - "5672:5672"   # The port for your Java app to connect
      - "15672:15672" # The port for the Dashboard UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password