global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082', 'host.docker.internal:8084']
        labels:
          application: 'lab04-services'