server:
  port: 8761 # Standard Eureka port

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false # Don't register yourself
    fetch-registry: false       # Don't pull list from yourself
    service-url:
      defaultZone: http://localhost:8761/eureka/